### ISSUE TITLE
In-Godot Compilation of Source Models into VMFB for IREE.GD Project

### ISSUE THREAD

**Issue by fire** [iree-gd/iree.gd#35]
### Describe the proposed feature and its relevance to inferencing

The current method of compiling source models like TensorFlow Lite into VMFB in the IREE.GD project involves an external Python script, which is awkward and interrupts the workflow within Godot.

### Context or use case

I propose the integration of a feature that allows for the direct compilation of source models into VMFB within the Godot environment itself. This would make the process more streamlined and user-friendly, enhancing the overall usability of the Godot game engine.

### Proposed solution

An alternative could be to continue using the current method, but this may not provide the same level of ease-of-use that in-Godot compilation could offer.

### Additional information

This feature request comes from a desire to improve the user experience of the IREE.GD project by simplifying the process of compiling source models into VMFB within the Godot game engine.

I don't think this can be easily done.

**Comment by RechieKho** [comment]
The headache part is that I need to compile the whole LLVM. I don't have the good spec as you, fire 😞 .
Would defer dealing with this till I have a big machine.

**Comment by fire** [comment]
Pausing for now
