### ISSUE TITLE
Code Linting on pull request.

### ISSUE THREAD

**Issue by RechieKho** [iree-gd/iree.gd#53]
### Describe the proposed feature and its relevance to inferencing

Having a workflow that lint the code on pull request would be nice.

**Comment by fire** [comment]
Godot Engine is adding precommit. This is a path for iree.gd to auto have linting.

**Comment by fire** [comment]
Lets do it

**Comment by RechieKho** [comment]
Sure, could you link me to the thing you are talking about? The precommit?  Also, I do remember @Ughuuu did add code linting on GitHub workflow, how would that differ from Godot's approach?

**Comment by fire** [comment]
https://github.com/godotengine/godot-cpp-template

**Comment by Ughuuu** [comment]
We do have linting on PR.

**Comment by fire** [comment]
Thanks
