### ISSUE TITLE
Use Vulkan backend on Android devices.

### ISSUE THREAD

**Issue by RechieKho** [iree-gd/iree.gd#84]
### Describe the proposed feature and its relevance to inferencing

Currently, we have three backend, Metal, Vulkan and VMVX (or cpu). The issue of VMVX is that it is slow from my experience (could be outdated information since the last time I test it is a year ago). Moreover, about 85% of android supports Vulkan, based on the [android developer website](https://developer.android.com/games/develop/vulkan/overview). I believe it would be wise to just let android run on Vulkan.

This doesn't means that we dump everything about VMVX. We could wait for the technology for VMVX to be fast enough to be run on devices. For now, we could introduce CMake build option to force a VMVX backend for people who are opted to try out this widely supported but not too fast backend.

### Proposed solution

Let android's backend to be Vulkan. Introduce CMake build option for force VMVX backend and implement preprocessor directive for it.

**Comment by fire** [comment]
Yes. lets do it

**Comment by fire** [comment]
> Ben had a GUI program running simple filters here: https://github.com/iree-org/iree-experimental/tree/scotttodd-ml-overlay/cpp/ml_overlay. IIRC, the C++ code there was sharing a Vulkan context between the GUI application and the IREE runtime, with (close to? or TODO?) zero copy buffer transfers back and forth

From @scotttodd

**Comment by fire** [comment]
Syphon exists.

https://syphon.github.io/ 

if we cant make IREE and godot use the same graphics context we may be able to figure out how they share frames across GPU contexts. It's macOS and OpenGL but may still be an interesting resource

**Comment by ScottTodd** [comment]
VMVX is primarily a reference backend. It has the potential to be faster, but the "vector extensions" part of "virtual machine vector extensions" is nearly empty at the moment (IIRC microkernels changes the math there _slightly_, but not enough for most use cases).

For CPU, we suggest using llvm-cpu, but you do need to know about your deployment target architecture (and ideally CPU features) at compilation time to get the most out of llvm-cpu. See slide 9 of https://drive.google.com/file/d/1ikgOdZxnMz1ExqwrAiuTY9exbe3yMWbB/view - Android applications already multi-target (build for multiple architectures / CPU variants) for the entire application, so doing the same for performance critical subsections shouldn't be that much of a stretch either. I'm not sure how that interacts with iree.gd and Godot in general though.

One thing about Vulkan for GPU on Android: we require some semi-modern features like timeline semaphores. Older devices either won't be able to use IREE + Vulkan or would need a compatibility layer like https://github.com/KhronosGroup/Vulkan-ExtensionLayer . I think our docs at https://iree.dev/guides/deployment-configurations/gpu-vulkan/ should be reasonably up-to-date, but feel free to report any issues or ask for clarification.

**Comment by RechieKho** [comment]
I'll be focusing on this now.

For now, I'll just migrate the backend to Vulkan for android. Due to Vulkan not being used in compatibility (mobile) mode of Godot, it will create its own instance of Vulkan. This raises the question in which how can we share same frame across different API (I think Godot on mobile will be using OpenGL instead). 

For llvm-cpu, I guess I'll look into it and see whether it has the potential to be used as web backend...

**Comment by fire** [comment]
Too bad have no idea how to add webgpu to godot web
