### ISSUE TITLE
Document the current state of Backends / Platforms support

### ISSUE THREAD

**Issue by Ivorforce** [iree-gd/iree.gd#88]
### Describe the proposed feature and its relevance to inferencing

It would be good to better explain the backends.

In particular, I'm missing the following:
- CPU Builds: Are they supported? (I think yes, but the readme almost implies it's GPU only)
- Web / WASM: What's the status here? (related to https://github.com/iree-org/iree/issues/8327)

### Context or use case

-

### Proposed solution

Just needs some adjustments to the readme for now.

### Additional information

-

**Comment by fire** [comment]
`vmvx` is the cpu version, it is quite slow so you'll have to scale down your compute problems.

**Comment by fire** [comment]
`vmx` implies that the Godot Engine web platform. can run `vmvx`, but not `webgpu`.

**Comment by fire** [comment]
What is your usecase of the web platform? Since we're unable to run a large model we didn't think it'll be useful for our problems.

**Comment by Ivorforce** [comment]
I'm more interested in running general compute problems than ML models specifically. Preparing a graph in torch / tf and having it execute in an accelerated fashion from GDScript would be my main use-case.

**Comment by Ivorforce** [comment]
Anyway, this issue is more concerned with full documentation of the supported backends as they exist now, rather than requesting a CPU backend. I may do that in a separate issue later.

**Comment by fire** [comment]
We implement vmvx on the Android platform, but since it is the cpu backend, it works on all platforms.

**Comment by fire** [comment]
https://iree-gd.github.io/iree.gd.docs/ has some updated documentation

**Comment by fire** [comment]
I'll close this for now. Let me know if updates are needed.
