### ISSUE TITLE
Pose detection is failing on Vulkan backend

### ISSUE THREAD

**Issue by RechieKho** [iree-gd/iree.gd#96]
### Issue description

This is the result on Vulkan

![image](https://github.com/user-attachments/assets/a64c79b6-7b14-445d-babd-b18f14d9bbd5)

This is the result on Metal backend. 

<img width="600" alt="Screenshot 2024-11-03 at 10 23 09 PM" src="https://github.com/user-attachments/assets/9a97fd58-7730-4111-b274-f273184756fa">

You can clearly see that Vulkan one is dreadfully wrong. 

### Steps to reproduce

Run the `res://scenes/pose_detection/pose_detection.tscn` on operating system that uses Vulkan backend (Windows and android). 

### Using a released version?

v0.0.2

### What OS? Any other relevant information? (iree.gd revision, System information)

Windows 11

**Comment by RechieKho** [comment]
Although there is an alternate model that seems to work, I'll still make this thing remain open for IREE side to check out what happened.

**Comment by fire** [comment]
> Joseph — Yesterday at 14:10
>
> I know the post is old as heck, but I forgot to reply.  :rip: 
>
> When the model goes off the rails like this it can sometimes be because rows and columns get flipped.  I had an issue with a pose model a year and change ago that came about for two reasons: first is it was trained on BGR instead of RGB and second was it got all the images in column-major instead of row-major because of silly matrix ordering, so all the images were effectively rotated 90 degrees.  It worked a bit, but not great, for these reasons.  Might be worth checking if either is still a problem.

**Comment by fire** [comment]
> Ivorius — Yesterday at 15:14
> Sounds reasonable. transpose and try again!

**Comment by fire** [comment]
The current release is still broken even if it is fixed on the master.

**Comment by fire** [comment]
Closing due to workaround shipped in https://github.com/iree-gd/iree.gd/releases/tag/v0.0.3
